### ISSUE TITLE
Action isn't working when Vercel uses cached URL

### ISSUE THREAD

**Issue by aaron-binary** [aaron-binary/vercel-preview-url-action#6]
1. Create a PR and let Vercel create a deployment URL.
2. Close that PR.
3. Create a new PR using the branch from step 1.
4. Vercel will comment immediately with the preview URL so the edit event will not trigger.

**Comment by aaron-binary** [comment]
Can be worked around by expanding the triggers:

```YML
on:
  issue_comment:
    types: [created, edited]
```
